sudo: enabled
services:
  - docker
language: node_js
node_js:
  - "12"
env:
- KUBECTL_VERSION=1.12.0
before_install:
  - curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v${KUBECTL_VERSION}/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
install:
  - npm install
script:
  - npm run test
