sudo: enabled
services:
  - docker
language: node_js
node_js:
  - "12"
before_install:
  - curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.12.0/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
install:
  - npm install
script:
  - npm run test
